server:
  port: 2008

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/23Vvrangler/Examen-Parcial-De-DAD.git #Tu reposritorio
          searchPaths: config-data #Crearemos esta carpeta
          default-label: main #Rama de tu repositorio

  security:
    user:
      name: root
      password: 123456